### ISSUE TITLE
Can not use in no-module project.

### ISSUE THREAD

**Issue by adamglin0** [sellmair/compose-hot-reload#1]
if use compose-hot-reload in root build.gradle.kts, will throw 'can't locate tasks that match ::compileUIKotlinJVM, ..use :compileUIKotlinJVM instead'

**Comment by sellmair** [comment]
Should be fixed by:
81a155855c4f9fe8fe665dc5292a2cc1fd3700c7

**Comment by sellmair** [comment]
Maybe you can check if build `1.0.0-dev.13` works for you?
